# Generated by Django 6.0.6 on 2026-06-26 09:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/images/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='equipment/documents/')),
                ('is_available', models.BooleanField(default=True)),
                ('min_booking_time', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('max_booking_time', models.DurationField(blank=True, null=True)),
                ('gap_after_booking', models.DurationField(blank=True, null=True)),
                ('book_ahead_limit', models.DurationField(blank=True, null=True)),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('teal', 'Teal'), ('blue', 'Blue'), ('pink', 'Pink'), ('tan', 'Tan'), ('peach', 'Peach'), ('green', 'Green'), ('rose', 'Rose')], default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.equipment')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
